// PrismaClient is generated by running: pnpm db:generate
// This import will work after running: pnpm db:generate
// @ts-expect-error - PrismaClient is generated dynamically, TypeScript error is expected until generation
import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

// Prisma 7: Connection URL is configured in prisma.config.ts
// The PrismaClient reads from DATABASE_URL environment variable automatically
export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['query', 'error', 'warn'] : ['error'],
  });

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;

