// PrismaClient is generated by running: pnpm db:generate
// This import will work after running: pnpm db:generate
import pkg from '@prisma/client';
const { PrismaClient } = pkg;
import type { PrismaClient as PrismaClientType } from '@prisma/client';

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClientType | undefined;
};

// Prisma 6: Connection URL is read from DATABASE_URL environment variable
// Prisma 6 has stable MongoDB support (Prisma 7 has known compatibility issues)
export const prisma =
  globalForPrisma.prisma ??
  (new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['query', 'error', 'warn'] : ['error'],
  }) as unknown as PrismaClientType);

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;

