// Simple script to create placeholder icons
const fs = require('fs');
const path = require('path');

// Create a simple 1024x1024 PNG placeholder
// For now, we'll use Expo's default icon generation
console.log('Icons will be generated by Expo prebuild');
